//! Messages exchanged over the management channel and the ingest endpoint.
//!
//! # Forward compatibility
//!
//! Every envelope carries a `kind` string rather than an externally-tagged
//! enum, so a peer that receives a kind it does not know can log and drop the
//! frame instead of failing to deserialise the connection. That property is
//! load-bearing: a v1 instance will still be talking to the backend years after
//! v3 ships, and a single unknown frame must never take the channel down.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A framed message on the management channel.
///
/// `payload` stays as raw JSON until `kind` has been matched, so unknown kinds
/// cost nothing to skip.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Envelope {
    pub kind: String,
    pub payload: serde_json::Value,
}

impl Envelope {
    pub fn new<T: Serialize>(kind: &str, payload: &T) -> Result<Self, serde_json::Error> {
        Ok(Self {
            kind: kind.to_string(),
            payload: serde_json::to_value(payload)?,
        })
    }

    /// Decode the payload, or `None` when this is not the expected kind.
    ///
    /// Returning `None` rather than an error for a kind mismatch is what lets
    /// a receive loop skip unknown frames without special-casing each one.
    pub fn decode<T: for<'de> Deserialize<'de>>(&self, kind: &str) -> Option<T> {
        if self.kind != kind {
            return None;
        }
        serde_json::from_value(self.payload.clone()).ok()
    }
}

// ---------------------------------------------------------------------------
// Enrollment
// ---------------------------------------------------------------------------

/// Sent once, over HTTPS, to exchange an operator-pasted enrollment code for
/// long-lived instance credentials.
#[derive(Clone, Serialize, Deserialize)]
pub struct EnrollRequest {
    /// Short-lived code the operator copied from the cloud console.
    pub enrollment_code: String,
    /// Stable identifier the instance generates once and persists.
    pub instance_id: Uuid,
    /// Reported for support and skew diagnostics only — never trusted for
    /// authorization decisions.
    pub agent_version: String,
}

impl std::fmt::Debug for EnrollRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EnrollRequest")
            .field("enrollment_code", &"[REDACTED]")
            .field("instance_id", &self.instance_id)
            .field("agent_version", &self.agent_version)
            .finish()
    }
}

#[derive(Clone, Serialize, Deserialize)]
pub struct EnrollResponse {
    pub tenant_id: Uuid,
    /// Bearer token for the management channel and the ingest endpoint.
    /// Scoped to this instance and this tenant, nothing else.
    pub instance_token: String,
    /// What the tenant's current plan permits. May shrink on downgrade.
    ///
    /// Defaults to empty when absent, per the additive-changes rule: a backend
    /// predating this field must still be understood, and an instance that
    /// cannot tell what it is allowed to do should assume nothing rather than
    /// everything.
    #[serde(default)]
    pub capabilities: Vec<crate::Capability>,
}

impl std::fmt::Debug for EnrollResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EnrollResponse")
            .field("tenant_id", &self.tenant_id)
            .field("instance_token", &"[REDACTED]")
            .field("capabilities", &self.capabilities)
            .finish()
    }
}

// ---------------------------------------------------------------------------
// Telemetry
// ---------------------------------------------------------------------------

/// One span as shipped by an instance.
///
/// Deliberately flat and self-describing: the cloud must be able to accept a
/// batch from an instance several versions behind without a translation table.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SpanRecord {
    pub trace_id: String,
    pub span_id: String,
    pub name: String,
    /// Milliseconds since the Unix epoch. Used for querying and retention.
    ///
    /// NEVER used for billing: the cloud meters on its own receive time, so a
    /// wrong clock on an instance cannot move money.
    pub ts_millis: i64,
    pub duration_ms: f64,
    #[serde(default)]
    pub attributes: std::collections::BTreeMap<String, String>,
}

/// A batch posted to the ingest endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TelemetryBatch {
    /// Generated by the instance before the first attempt and reused for every
    /// retry of these exact bytes. The backend binds it to the authenticated
    /// instance and payload digest before treating a retry as idempotent.
    pub submission_id: Uuid,
    pub spans: Vec<SpanRecord>,
}

/// Ingest outcome. A client clears a submission only when the id matches and
/// `processed_spans` covers the entire attempted batch.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IngestAck {
    pub submission_id: Uuid,
    /// Records fully handled by the gateway and safe to remove client-side.
    pub processed_spans: usize,
    /// Records retained after quota sampling. May be lower than `processed`.
    pub stored_spans: usize,
    /// Bytes the cloud will bill for — echoed back so the operator can
    /// reconcile their own figure against the invoice.
    pub metered_bytes: u64,
    /// Present when the batch was accepted but the tenant is degraded, e.g.
    /// over quota and now sampling. The instance must surface this, not hide it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warning: Option<crate::Unavailable>,
}

// ---------------------------------------------------------------------------
// Backups
// ---------------------------------------------------------------------------

/// Instance asks where to put a backup.
///
/// The cloud replies with a presigned destination; backup bytes then travel
/// instance -> object storage **directly**. They never transit the control
/// plane, which is what keeps our bandwidth cost at zero and stops us becoming
/// a throughput bottleneck.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BackupTargetRequest {
    pub instance_id: Uuid,
    /// What is being backed up, e.g. a service or database name.
    pub source: String,
    pub estimated_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BackupTarget {
    pub backup_id: Uuid,
    /// Presigned PUT destination, scoped to this object key alone.
    pub upload_url: String,
    pub object_key: String,
    pub expires_at_millis: i64,
}

/// Instance reports the upload finished. Until this arrives the object is not
/// a backup: a partial multipart upload must never be counted as one.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BackupCompleted {
    pub backup_id: Uuid,
    pub bytes: u64,
    /// SHA-256 of the uploaded object, so restore can detect corruption before
    /// the customer discovers it during an actual disaster.
    pub checksum_sha256: String,
}

// ---------------------------------------------------------------------------
// Liveness
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Heartbeat {
    pub instance_id: Uuid,
    /// Reported so the cloud can keep a DNS A record current for instances
    /// with dynamic addresses.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_ip: Option<String>,
    /// Local spool depth. A growing value is the signal that the instance is
    /// buffering because we are failing it.
    pub pending_spool_bytes: u64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn envelope_round_trips() {
        let hb = Heartbeat {
            instance_id: Uuid::nil(),
            public_ip: None,
            pending_spool_bytes: 42,
        };
        let env = Envelope::new("heartbeat", &hb).unwrap();
        let back: Heartbeat = env.decode("heartbeat").unwrap();
        assert_eq!(back.pending_spool_bytes, 42);
    }

    #[test]
    fn unknown_kind_decodes_to_none_rather_than_erroring() {
        // The forward-compatibility guarantee: a v1 peer receiving a v3 frame
        // must be able to skip it and keep the channel open.
        let env = Envelope::new("some_future_kind", &serde_json::json!({"x": 1})).unwrap();
        assert!(env.decode::<Heartbeat>("heartbeat").is_none());
    }

    #[test]
    fn span_attributes_default_when_absent() {
        // Older instances predate `attributes`; their batches must still parse.
        let json = r#"{
            "trace_id":"t","span_id":"s","name":"GET /",
            "ts_millis":1700000000000,"duration_ms":1.5
        }"#;
        let span: SpanRecord = serde_json::from_str(json).unwrap();
        assert!(span.attributes.is_empty());
    }

    #[test]
    fn ingest_ack_omits_warning_when_healthy() {
        let ack = IngestAck {
            submission_id: Uuid::new_v4(),
            processed_spans: 3,
            stored_spans: 3,
            metered_bytes: 100,
            warning: None,
        };
        let s = serde_json::to_string(&ack).unwrap();
        assert!(
            !s.contains("warning"),
            "healthy ack should not carry a warning key: {s}"
        );
    }

    #[test]
    fn enrollment_debug_output_redacts_credentials() {
        let request = EnrollRequest {
            enrollment_code: "secret-code".into(),
            instance_id: Uuid::new_v4(),
            agent_version: "test".into(),
        };
        let response = EnrollResponse {
            tenant_id: Uuid::new_v4(),
            instance_token: "inst_secret".into(),
            capabilities: vec![],
        };

        assert!(!format!("{request:?}").contains("secret-code"));
        assert!(!format!("{response:?}").contains("inst_secret"));
    }
}
