#!/usr/bin/env python3
"""Split the generated Temps CLI catalog into one reference per command group."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HEADING = re.compile(r"^## `([^`]+)`(?:.*)$", re.MULTILINE)
SUBHEADING = re.compile(r"^### `([^`]+)`(?:.*)$", re.MULTILINE)
FOOTER = re.compile(r"^---\n\n## Examples\n", re.MULTILINE)


def slug(command: str) -> str:
    value = command.lower().replace(":", "-")
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    if not value:
        raise ValueError(f"cannot create filename for command {command!r}")
    return value


def anchor(title: str) -> str:
    value = title.lower().replace(":", "")
    return re.sub(r"[^a-z0-9 -]", "", value).replace(" ", "-")


def split_catalog(source: Path, destination: Path) -> list[tuple[str, Path]]:
    text = source.read_text(encoding="utf-8")
    matches = list(HEADING.finditer(text))
    if not matches:
        raise ValueError(f"no command headings found in {source}")
    footer = FOOTER.search(text)
    catalog_end = footer.start() if footer else len(text)

    destination.mkdir(parents=True, exist_ok=True)
    generated: list[tuple[str, Path]] = []
    expected_names: set[str] = {"INDEX.md"}

    for index, match in enumerate(matches):
        command = match.group(1)
        end = matches[index + 1].start() if index + 1 < len(matches) else catalog_end
        body = text[match.start() : end].rstrip() + "\n"
        filename = f"{slug(command)}.md"
        expected_names.add(filename)
        output = destination / filename
        header = (
            "<!-- Generated from skills/temps-cli/references/COMMANDS.md. "
            "Do not edit manually. -->\n\n"
            f"# `{command}` command reference\n\n"
            "Apply [the CLI runtime and safety contract](../cli-runtime.md) "
            "before executing a command. Runtime `--help` is authoritative.\n\n"
        )
        subcommands = [item.group(1) for item in SUBHEADING.finditer(body)]
        if (header + body).count("\n") + 1 > 300 and subcommands:
            header += "## Contents\n\n"
            header += "\n".join(
                f"- [`{subcommand}`](#{anchor(subcommand)})" for subcommand in subcommands
            )
            header += "\n\n"
        output.write_text(header + body, encoding="utf-8")
        generated.append((command, output))

    for old_file in destination.glob("*.md"):
        if old_file.name not in expected_names:
            old_file.unlink()

    index_lines = [
        "<!-- Generated by scripts/generate_command_references.py. -->",
        "",
        "# Temps CLI command groups",
        "",
        "Read one command-group reference at a time. Use runtime `--help` when",
        "syntax may have changed.",
        "",
    ]
    for command, output in generated:
        index_lines.append(f"- [`{command}`]({output.name})")
    index_lines.append("")
    (destination / "INDEX.md").write_text("\n".join(index_lines), encoding="utf-8")
    return generated


def main() -> int:
    skill_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=skill_root.parent / "temps-cli" / "references" / "COMMANDS.md",
    )
    parser.add_argument(
        "--destination",
        type=Path,
        default=skill_root / "references" / "commands",
    )
    args = parser.parse_args()
    generated = split_catalog(args.source.resolve(), args.destination.resolve())
    print(f"generated {len(generated)} command references in {args.destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
